### ISSUE TITLE
Pluggable, open container.

### ISSUE THREAD

**Issue by LucasMartinCalderon** [AIforGoodSimulator/model-server#14]
Will the web server be a separate container?
Where do we intend to save the Results and Graphs? Volume/NFS?
Are we going to run this on ACI via docker context? or AKS?
How will new models and their dependencies be added/integrated into the model server?
Or will this just become the base image to build a multistage container for new models?
Orca is not available via pip and requires some dependency management. Alternatives?

Awaiting more info.

**Comment by pardf** [comment]
@titorenko @billlyzhaoyh @syedimra953

**Comment by syedimra953** [comment]
@LucasMartinCalderon 
Please find below my response - waiting for complete response from @sumitpapnai  and Tejdeep Singh.

Will the web server be a separate container? -- Yes - we will be running it as seperate container
Where do we intend to save the Results and Graphs? Volume/NFS?  -- It will be likely in Volume (others can confirm)
Are we going to run this on ACI via docker context? or AKS?  - It will be I guess via AKS
How will new models and their dependencies be added/integrated into the model server? 
Or will this just become the base image to build a multistage container for new models? - yes - this will be base image which will be used to build multistage containers for other models
Orca is not available via pip and requires some dependency management. Alternatives? -- I am not sure on this.

**Comment by pardf** [comment]
@syedimra953 @LucasMartinCalderon 
    Please find below my response - waiting for complete response from @sumitpapnai and Tejdeep Singh.Will the web server be a separate container? -- Yes - we will be running it as separate container
    Where do we intend to save the Results and Graphs? Volume/NFS? -- It will be likely in Volume (others can confirm): 
              **Tej: Bucket Storage**
    Are we going to run this on ACI via docker context? or AKS? - It will be I guess via AKS: 
              **Tej: AKS**
    How will new models and their dependencies be added/integrated into the model server? 
             **Tej: Model server is just a framework you can have inception file to run your model on that model server. all commands are in github documentation already.**
    Or will this just become the base image to build a multistage container for new models? - yes - this will be base image which will be used to build multistage containers for other models. 
              **Tej: Is the question here on how to inception/Run different models with model server ?**
     Orca is not available via pip and requires some dependency management. Alternatives? -- I am not sure on this. 
              **Tej: Which container or AKS does not have orca available. need to know the name.**
