### ISSUE TITLE
Incorporate mouse-over helping text to model input parameters

### ISSUE THREAD

**Issue by pardf** [AIforGoodSimulator/model-server#16]

**Comment by pardf** [comment]
@titorenko hi Kostya can you comment on how this can be done? Thanks

**Comment by titorenko** [comment]
No idea, check dash help?

**Comment by pardf** [comment]
https://community.plotly.com/t/hoverinfo-on-dash-datatable/23436

**Comment by pardf** [comment]
Completed by the student team @AIforGoodSimulator/db-student . Thanks!
