### ISSUE TITLE
M: prototype agent-based model

### ISSUE THREAD

**Issue by titorenko** [AIforGoodSimulator/model-server#4]

**Comment by titorenko** [comment]
Some Moria info:

https://www.notion.so/Refugee-activity-for-Moria-ffc8e8b50c414375a6f9fd2e8cd8a2ad

https://www.notion.so/v1-ConceptualModel-a67130a74bb64518a5834f5bdabb1f77

Simulation example for city:

https://www.sciencedirect.com/science/article/pii/S0198971514001367

**Comment by pardf** [comment]
@vekimenko prototype awesome!
Run_model - http://207.154.208.109:8050/sim/run_model
Report - http://207.154.208.109:8050/sim/report?model=agent-based-model&profile=small&camp=Moria&intervention=baseline
Result - http://207.154.208.109:8050/sim/results?model=agent-based-model&profile=small&camp=Moria

**Comment by pardf** [comment]
Run_model - http://139.59.146.160:8050/sim/run_model
Report - http://139.59.146.160:8050/sim/report?model=agent-based-model&profile=small&camp=Moria&intervention=baseline
Result - http://139.59.146.160:8050/sim/results?model=agent-based-model&profile=small&camp=Moria

**Comment by pardf** [comment]
ABM model available in alpha release
